from __future__ import annotations

from dataclasses import dataclass
import math
import random

from brain import BrainGenome

from .food_world import (
    EpisodeResult,
    FoodWorld,
    FoodWorldConfig,
    StepTrace,
    WorldObstacle,
)
from .geometry import clamp, distance, wrap_angle


@dataclass(frozen=True)
class RoomFoodWorldConfig(FoodWorldConfig):
    """A two-room navigation task with one movable doorway."""

    door_width: float = 1.8
    wall_thickness: float = 0.45
    wall_sensor_range: float = 2.8
    collision_penalty: float = 0.25
    use_wall_sensors: bool = True
    use_position_sensors: bool = True

    def __post_init__(self) -> None:
        if self.door_width <= 0 or self.door_width >= self.size * 0.6:
            raise ValueError("door_width must be positive and smaller than the room.")
        if self.wall_thickness <= 0 or self.wall_thickness >= self.size * 0.2:
            raise ValueError("wall_thickness must be positive and smaller than the room.")
        if self.wall_sensor_range <= 0:
            raise ValueError("wall_sensor_range must be positive.")
        if self.collision_penalty < 0:
            raise ValueError("collision_penalty cannot be negative.")


@dataclass(frozen=True)
class RoomScenarioSignature:
    """The categorical layout factors used to balance diagnostic rooms."""

    orientation: str
    start_side: str
    door_side: str


@dataclass(frozen=True)
class _RoomLayout:
    orientation: str
    wall_position: float
    door_center: float
    door_low: float
    door_high: float
    obstacles: tuple[WorldObstacle, WorldObstacle]


class RoomFoodWorld(FoodWorld):
    """Food is across a wall, so the agent must discover and use a doorway."""

    input_size = 9

    def __init__(self, config: RoomFoodWorldConfig | None = None) -> None:
        self.config = config or RoomFoodWorldConfig()

    @staticmethod
    def layout_orientation_for_seed(seed: int) -> str:
        """Return the wall orientation without running a full episode."""
        return RoomFoodWorld._draw_orientation(random.Random(seed))

    def scenario_signature_for_seed(self, seed: int) -> RoomScenarioSignature:
        """Describe the layout factors generated by a seed."""
        rng = random.Random(seed)
        layout = self._make_layout(rng)
        agent_x, agent_y, _, _ = self._place_agent_and_food(rng, layout)
        start_axis = (
            agent_x - layout.wall_position
            if layout.orientation == "vertical"
            else agent_y - layout.wall_position
        )
        return RoomScenarioSignature(
            orientation=layout.orientation,
            start_side="positive" if start_axis > 0 else "negative",
            door_side="positive" if layout.door_center > 0 else "negative",
        )

    def evaluate(
        self,
        genome: BrainGenome,
        rng: random.Random,
        record_trace: bool = False,
    ) -> EpisodeResult:
        layout = self._make_layout(rng)
        agent_x, agent_y, food_x, food_y = self._place_agent_and_food(rng, layout)
        heading = rng.uniform(-math.pi, math.pi)
        state = genome.initial_state()
        score = 0.0
        collision_count = 0
        previous_route_distance = self._route_distance(
            agent_x,
            agent_y,
            food_x,
            food_y,
            layout,
        )
        food_distance = distance(agent_x, agent_y, food_x, food_y)
        trace: list[StepTrace] | None = [] if record_trace else None

        if trace is not None:
            trace.append(
                StepTrace(
                    step=0,
                    agent_x=agent_x,
                    agent_y=agent_y,
                    heading=heading,
                    food_x=food_x,
                    food_y=food_y,
                    distance=food_distance,
                    score=score,
                    observation=self._observe_room(
                        agent_x,
                        agent_y,
                        heading,
                        food_x,
                        food_y,
                        layout.obstacles,
                    ),
                    output=[0.0 for _ in range(self.output_size)],
                    hidden=state.hidden.copy(),
                )
            )

        for step in range(1, self.config.max_steps + 1):
            observation = self._observe_room(
                agent_x,
                agent_y,
                heading,
                food_x,
                food_y,
                layout.obstacles,
            )
            output, state = genome.activate(observation, state)
            turn_signal = output[1] - output[0]
            move_signal = max(0.0, output[2])
            heading = wrap_angle(heading + turn_signal * self.config.turn_speed)

            movement = move_signal * self.config.move_speed
            dx = math.cos(heading) * movement
            dy = math.sin(heading) * movement
            agent_x, agent_y, collided = self._move(
                agent_x,
                agent_y,
                dx,
                dy,
                layout.obstacles,
            )

            route_distance = self._route_distance(
                agent_x,
                agent_y,
                food_x,
                food_y,
                layout,
            )
            score += (
                previous_route_distance - route_distance
            ) * self.config.approach_reward
            score -= self.config.time_penalty
            if collided:
                collision_count += 1
                score -= self.config.collision_penalty
            previous_route_distance = route_distance
            food_distance = distance(agent_x, agent_y, food_x, food_y)

            if trace is not None:
                trace.append(
                    StepTrace(
                        step=step,
                        agent_x=agent_x,
                        agent_y=agent_y,
                        heading=heading,
                        food_x=food_x,
                        food_y=food_y,
                        distance=food_distance,
                        score=score,
                        observation=observation,
                        output=output,
                        hidden=state.hidden.copy(),
                        collided=collided,
                    )
                )

            if food_distance <= self.config.eat_radius:
                score += self.config.eat_reward
                if trace is not None:
                    trace[-1].score = score
                return EpisodeResult(
                    score=score,
                    ate_food=True,
                    steps=step,
                    final_distance=food_distance,
                    trace=trace,
                    obstacles=list(layout.obstacles),
                    collisions=collision_count,
                )

        return EpisodeResult(
            score=score,
            ate_food=False,
            steps=self.config.max_steps,
            final_distance=food_distance,
            trace=trace,
            obstacles=list(layout.obstacles),
            collisions=collision_count,
        )

    def _make_layout(self, rng: random.Random) -> _RoomLayout:
        half = self.config.size / 2
        orientation = self._draw_orientation(rng)
        wall_position = rng.uniform(-self.config.size * 0.1, self.config.size * 0.1)
        door_center = rng.uniform(-self.config.size * 0.24, self.config.size * 0.24)
        door_low = door_center - self.config.door_width / 2
        door_high = door_center + self.config.door_width / 2
        wall_half = self.config.wall_thickness / 2

        if orientation == "vertical":
            obstacles = (
                WorldObstacle(
                    wall_position - wall_half,
                    -half,
                    wall_position + wall_half,
                    door_low,
                ),
                WorldObstacle(
                    wall_position - wall_half,
                    door_high,
                    wall_position + wall_half,
                    half,
                ),
            )
        else:
            obstacles = (
                WorldObstacle(
                    -half,
                    wall_position - wall_half,
                    door_low,
                    wall_position + wall_half,
                ),
                WorldObstacle(
                    door_high,
                    wall_position - wall_half,
                    half,
                    wall_position + wall_half,
                ),
            )
        return _RoomLayout(
            orientation=orientation,
            wall_position=wall_position,
            door_center=door_center,
            door_low=door_low,
            door_high=door_high,
            obstacles=obstacles,
        )

    @staticmethod
    def _draw_orientation(rng: random.Random) -> str:
        return "vertical" if rng.random() < 0.5 else "horizontal"

    def _place_agent_and_food(
        self,
        rng: random.Random,
        layout: _RoomLayout,
    ) -> tuple[float, float, float, float]:
        side = -1 if rng.random() < 0.5 else 1
        agent_offset = rng.uniform(self.config.size * 0.2, self.config.size * 0.34)
        food_offset = rng.uniform(self.config.size * 0.2, self.config.size * 0.34)
        lane_options = (-self.config.size * 0.35, self.config.size * 0.35)
        lane = max(lane_options, key=lambda value: abs(value - layout.door_center))
        jitter = self.config.size * 0.04
        agent_lane = lane + rng.uniform(-jitter, jitter)
        food_lane = lane + rng.uniform(-jitter, jitter)

        if layout.orientation == "vertical":
            return (
                layout.wall_position + side * agent_offset,
                agent_lane,
                layout.wall_position - side * food_offset,
                food_lane,
            )
        return (
            agent_lane,
            layout.wall_position + side * agent_offset,
            food_lane,
            layout.wall_position - side * food_offset,
        )

    def _observe_room(
        self,
        agent_x: float,
        agent_y: float,
        heading: float,
        food_x: float,
        food_y: float,
        obstacles: tuple[WorldObstacle, ...],
    ) -> list[float]:
        observation = super()._observe(
            agent_x,
            agent_y,
            heading,
            food_x,
            food_y,
        )
        if not self.config.use_position_sensors:
            observation[3] = 0.0
            observation[4] = 0.0
        if not self.config.use_wall_sensors:
            observation.extend((0.0, 0.0, 0.0))
            return observation
        for offset in (math.pi / 4, 0.0, -math.pi / 4):
            ray_angle = heading + offset
            ray_distance = self._ray_distance(
                agent_x,
                agent_y,
                math.cos(ray_angle),
                math.sin(ray_angle),
                obstacles,
            )
            proximity = 1.0 - min(
                ray_distance,
                self.config.wall_sensor_range,
            ) / self.config.wall_sensor_range
            observation.append(proximity)
        return observation

    def _ray_distance(
        self,
        origin_x: float,
        origin_y: float,
        direction_x: float,
        direction_y: float,
        obstacles: tuple[WorldObstacle, ...],
    ) -> float:
        half = self.config.size / 2
        distances = []
        if direction_x > 1e-9:
            distances.append((half - origin_x) / direction_x)
        elif direction_x < -1e-9:
            distances.append((-half - origin_x) / direction_x)
        if direction_y > 1e-9:
            distances.append((half - origin_y) / direction_y)
        elif direction_y < -1e-9:
            distances.append((-half - origin_y) / direction_y)

        for obstacle in obstacles:
            hit = _ray_box_distance(
                origin_x,
                origin_y,
                direction_x,
                direction_y,
                obstacle,
            )
            if hit is not None:
                distances.append(hit)
        return min(distance for distance in distances if distance >= 0.0)

    def _move(
        self,
        agent_x: float,
        agent_y: float,
        dx: float,
        dy: float,
        obstacles: tuple[WorldObstacle, ...],
    ) -> tuple[float, float, bool]:
        half = self.config.size / 2
        raw_x = agent_x + dx
        raw_y = agent_y + dy
        next_x = clamp(raw_x, -half, half)
        next_y = clamp(raw_y, -half, half)
        collided = next_x != raw_x or next_y != raw_y

        if not _point_blocked(next_x, agent_y, obstacles):
            agent_x = next_x
        else:
            collided = True
        if not _point_blocked(agent_x, next_y, obstacles):
            agent_y = next_y
        else:
            collided = True
        return agent_x, agent_y, collided

    @staticmethod
    def _route_distance(
        agent_x: float,
        agent_y: float,
        food_x: float,
        food_y: float,
        layout: _RoomLayout,
    ) -> float:
        if layout.orientation == "vertical":
            same_side = (agent_x - layout.wall_position) * (
                food_x - layout.wall_position
            ) >= 0
        else:
            same_side = (agent_y - layout.wall_position) * (
                food_y - layout.wall_position
            ) >= 0
        if same_side:
            return distance(agent_x, agent_y, food_x, food_y)

        doorway_samples = [
            layout.door_low
            + (layout.door_high - layout.door_low) * index / 16
            for index in range(1, 16)
        ]
        if layout.orientation == "vertical":
            return min(
                distance(agent_x, agent_y, layout.wall_position, doorway)
                + distance(layout.wall_position, doorway, food_x, food_y)
                for doorway in doorway_samples
            )
        return min(
            distance(agent_x, agent_y, doorway, layout.wall_position)
            + distance(doorway, layout.wall_position, food_x, food_y)
            for doorway in doorway_samples
        )


def _point_blocked(
    x: float,
    y: float,
    obstacles: tuple[WorldObstacle, ...],
) -> bool:
    return any(
        obstacle.x_min <= x <= obstacle.x_max
        and obstacle.y_min <= y <= obstacle.y_max
        for obstacle in obstacles
    )


def _ray_box_distance(
    origin_x: float,
    origin_y: float,
    direction_x: float,
    direction_y: float,
    obstacle: WorldObstacle,
) -> float | None:
    near = 0.0
    far = float("inf")
    for origin, direction, low, high in (
        (origin_x, direction_x, obstacle.x_min, obstacle.x_max),
        (origin_y, direction_y, obstacle.y_min, obstacle.y_max),
    ):
        if abs(direction) < 1e-9:
            if origin < low or origin > high:
                return None
            continue
        first = (low - origin) / direction
        second = (high - origin) / direction
        if first > second:
            first, second = second, first
        near = max(near, first)
        far = min(far, second)
        if near > far:
            return None
    return near if far >= 0.0 else None
